version: '3.1'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  es:
    image: elasticsearch:8.0.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node